name: Industrialisation continue sur le serveur Alwaysdata
on: push
jobs:
  Connexion:
    runs-on: ubuntu-latest
    steps:
      - name: Connexion SSH avec le serveur
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd $HOME/www/
  Copy:
    needs: ssh
    runs-on: ubuntu-latest
    steps:
      - name: Copie des fichiers sur le serveur
        run: |
          git clone https://github.com/OpenRSI/flask_hello_world.git
          rsync -r ./flask_hello_world/ ./flask3
          rm -rf ./flask_hello_world          
