name: Industrialisation continue sur le serveur Alwaysdata
on: push
jobs:
  Connexion:
    runs-on: ubuntu-latest
    steps:
      - name: Connexion SSH avec le serveur
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd $HOME/www/
  Copy:
    needs: Connexion
    runs-on: ubuntu-latest
    steps:
      - name: Copie des fichiers sur le serveur
        run: |
          git clone https://github.com/OpenRSI/flask_hello_world.git
          # Vérifier si le répertoire de destination existe
          if [ -d ./flask33 ]; then
            rsync -r ./flask_hello_world/ ./flask33
            rm -rf ./flask_hello_world
            # Vérifier le code de sortie de la commande rsync
            if [ $? -eq 0 ]; then
              echo "Copie réussie"
            else
              echo "Échec de la copie"
              exit 1  # Quitter avec un code d'erreur
            fi
          else
            echo "Le répertoire de destination n'existe pas"
            exit 1  # Quitter avec un code d'erreur
          fi
  Restart:
    needs: Copy
    runs-on: ubuntu-latest
    steps:
      - name: Restart Alwaysdata site
        run: |
          curl -X POST --basic --user "${{ secrets.ALWAYSDATA_TOKEN }}:" https://api.alwaysdata.com/v1/site/${{ secrets.ALWAYSDATA_SITE_ID }}/restart/        

          
